/* eslint-disable @typescript-eslint/naming-convention */
const fontFamily = {
  font1: "'Encode Sans', Arial, sans-serif",
  font2: "'TT Norms Pro', Arial, sans-serif",
  font3: "'Montserrat', Arial, sans-serif",
};

const textVariants = {
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 16,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 64,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.13,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 24,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.33,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 14,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.71,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 64,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.13,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 32,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 1.75,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 24,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 12,
    fontWeight: 500,
    textTransform: 'uppercase',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 14,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.71,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 80,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.1,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 24,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.33,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 32,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 20,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.6,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 16,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 24,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 40,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.2,
  },
  '.v-': {
    fontFamily: fontFamily.font1,
    fontSize: 14,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.71,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 12,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 2.0,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 48,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.33,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 48,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.33,
  },
  '.v-': {
    fontFamily: fontFamily.font2,
    fontSize: 12,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.33,
  },
  '.v-12': {
    fontFamily: fontFamily.font2,
    fontSize: 12,
    fontWeight: 700,
    textTransform: 'uppercase',
    lineHeight: 1.67,
  },
  '.v-14': {
    fontFamily: fontFamily.font1,
    fontSize: 14,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.43,
  },
  '.v-14': {
    fontFamily: fontFamily.font2,
    fontSize: 14,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.43,
  },
  '.v-14': {
    fontFamily: fontFamily.font2,
    fontSize: 14,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.43,
  },
  '.v-16': {
    fontFamily: fontFamily.font2,
    fontSize: 16,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-16': {
    fontFamily: fontFamily.font2,
    fontSize: 16,
    fontWeight: 500,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-16': {
    fontFamily: fontFamily.font2,
    fontSize: 16,
    fontWeight: 700,
    textTransform: 'uppercase',
    lineHeight: 1.5,
  },
  '.v-16': {
    fontFamily: fontFamily.font3,
    fontSize: 16,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-32': {
    fontFamily: fontFamily.font2,
    fontSize: 32,
    fontWeight: 700,
    textTransform: 'initial',
    lineHeight: 1.25,
  },
  '.v-bs.h160-16': {
    fontFamily: fontFamily.font2,
    fontSize: 16,
    fontWeight: 500,
    textTransform: 'uppercase',
    lineHeight: 1.5,
  },
  '.v-bs.label110-12': {
    fontFamily: fontFamily.font2,
    fontSize: 12,
    fontWeight: 500,
    textTransform: 'uppercase',
    lineHeight: 2.0,
  },
  '.v-bs.label141-14': {
    fontFamily: fontFamily.font2,
    fontSize: 14,
    fontWeight: 500,
    textTransform: 'uppercase',
    lineHeight: 1.71,
  },
  '.v-bs.label150-16': {
    fontFamily: fontFamily.font1,
    fontSize: 16,
    fontWeight: 400,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
  '.v-xl.sub170-20': {
    fontFamily: fontFamily.font1,
    fontSize: 20,
    fontWeight: 300,
    textTransform: 'initial',
    lineHeight: 1.5,
  },
};

module.exports = { fontFamily, textVariants };
